server {
    listen 80;
    listen [::]:80;
    server_name files.zhangjianyong.top;

    location /.well-known/acme-challenge/ {
        root /var/www/letsencrypt;
        try_files $uri =404;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}
